pekko {
  actor {
    provider = "cluster"
        serializers {
          proto = "org.apache.pekko.remote.serialization.ProtobufSerializer"
        }
  }

  serialization-bindings {
    "com.ldm.infrastructure.serialization.protobuf.PingPong$Ping" = proto
    "com.ldm.infrastructure.serialization.protobuf.PingPong$Pong" = proto
  }

  remote.artery {
    canonical {
      hostname = ${clustering.hostname}
      port = ${clustering.port}
    }
  }

  cluster {
    # Unique ldmId for each node
    roles = [${clustering.ldmIdRole}]

    seed-nodes = [
        ${clustering.seed-node}
    ]

    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }
}

clustering {
    hostname = "host.docker.internal"
    hostname = ${?LDM_HOSTNAME}
    port = 6000
    port = ${?PEKKO_PORT}
    ldmIdRole = "ldmId-54f34e52-b466-49f8-b525-230cd107148b"
    ldmIdRole = ${?LDMID_ROLE}
    seed-node = "pekko://ClusterSystem@host.docker.internal:6000"
    seed-node = ${?CLUSTER_SEED_NODE}
}
