pekko {
  actor {
    provider = "cluster"
  }
  remote.artery {
    canonical {
      hostname = ${clustering.hostname}
      port = ${clustering.port}
    }
  }

  cluster {
    # Unique ldmId for each node
    roles = [${clustering.ldmIdRole}]

    seed-nodes = [
        ${clustering.seed-node}
    ]

    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }
}

clustering {
    hostname = "localhost"
    hostname = ${?LDM_HOSTNAME}
    port = 6000
    port = ${?PEKKO_PORT}
    ldmIdRole = "ldmId-54f34e52-b466-49f8-b525-230cd107148b"
    ldmIdRole = ${?LDMID_ROLE}
    seed-node = "pekko://ClusterSystem@localhost:6000"
    seed-node = ${?CLUSTER_SEED_NODE}
}
