# Quarkus Configuration
quarkus:
  http:
    port: ${QUARKUS_HTTP_PORT:8080}
  jib:
    platforms: linux/arm64
  log:
    category:
      "com.ldm":
        level: ${LOG_LEVEL:DEBUG}
      "org.apache.pekko":  # Enable debug logs for Apache Pekko
        level: ${LOG_LEVEL:INFO}
      "org.apa.pek.per.r2d.que.sca.QueryDao":
        level: INFO
      "org.apa.pek.per.r2d.que.sca.R2dbcReadJournal":
        level: INFO
      "org.apache.ratis":  # Base Ratis package
        level: ${RATIS_LOG_LEVEL:WARN}        # Adjust the level to WARN or ERROR to suppress INFO logs
      "org.apache.ratis.server": # Suppress logs related to the Raft server
        level: ${RATIS_LOG_LEVEL:WARN}
      "org.apache.ratis.server.impl": # Suppress logs for Raft server implementations
        level: ${RATIS_LOG_LEVEL:WARN}
      "org.apache.ratis.grpc": # Suppress gRPC-related Ratis logs
        level: ${RATIS_LOG_LEVEL:WARN}
      "org.apache.ratis.server.raftserver": # Suppress leader election logs
        level: ${RATIS_LOG_LEVEL:WARN}
      "org.hibernate": DEBUG
  container-image:
    build: true
    push: false
    name: local-domain-manager
    group: tienhngnguyen
    registry: docker.io
  cache:
    caffeine:
      initial-capacity: ${CACHE_CAFFEINE_INITIAL_CAPACITY:100}
      maximum-size: ${CACHE_CAFFEINE_MAXIMUM_SIZE:1000}
      expire-after-write: ${CACHE_CAFFEINE_EXPIRE_AFTER_WRITE:15M}
      expire-after-access: ${CACHE_CAFFEINE_EXPIRE_AFTER_ACCESS:30M}
  datasource:
    db-kind: ${DB_KIND:postgresql}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:passw0rd}
    jdbc:
      url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/ldm_migrations}
    max-size: 10 # Maximum number of connections in the pool
    min-size: 1  # Minimum number of connections in the pool
    acquisition-timeout: 5 # Timeout in seconds for acquiring a connection
  liquibase:
    migrate-at-start: ${LIQUIBASE_MIGRATE_AT_START:true}
    clean-at-start: ${LIQUIBASE_CLEAN_AT_START:true}   # Drops the schema before migration
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  hibernate-orm:
    database:
      generation: ${DB_HIBERNATE_DB_GENERATION:none} #drop-and-create
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
# LDM Configuration
ldm:
  id: ${LDM_ID:54f34e52-b466-49f8-b525-230cd107148b}
  #enable-cluster-monitoring: ${LDM_ENABLE_CLUSTER_MONITORING:false}
  latencies-check:
    timeout: ${LDM_LATENCY_CHECK_TIMEOUT:5}
    interval: ${LDM_LATENCY_CHECK_INTERVAL:15}
    max-retry: ${LDM_LATENCY_CHECK_MAX_RETRY:3}
  proposal:
    interval: ${LDM_PROPOSAL_INTERVAL:15}
    request-timeout: ${LDM_PROPOSAL_REQUEST_TIMEOUT:20}
    threshold: ${LDM_PROPOSAL_THRESHOLD:25}
    scaling-factor: ${LDM_PROPOSAL_SCALING_FACTOR:20}
  voting:
    threshold: ${LDM_VOTING_THRESHOLD:0.3}
    scaling-factor: ${LDM_VOTING_SCALING_FACTOR:10}
# Raft Configuration
raft:
  server:
    id: ${LDM_ID:54f34e52-b466-49f8-b525-230cd107148b}
    host: ${LDM_HOSTNAME:localhost}
    port: ${RAFT_SERVER_PORT:4000}
    storage:
      dir: ${RAFT_STORAGE_DIR:raft-storage}
  cluster:
    id: ${RAFT_CLUSTER_ID:2335173a-0958-4712-b7f2-7c6a02abe5d5}
    peers:
      - id: ${CLUSTER_PEER_1_ID:54f34e52-b466-49f8-b525-230cd107148b}
        host: ${CLUSTER_PEER_1_HOST:localhost}
        port: ${CLUSTER_PEER_1_PORT:4000}
      - id: ${CLUSTER_PEER_2_ID:36f06b8b-cd19-4c72-a9a6-2f37baf4a422}
        host: ${CLUSTER_PEER_2_HOST:localhost}
        port: ${CLUSTER_PEER_2_PORT:4001}
      - id: ${CLUSTER_PEER_3_ID:66472086-5a7b-461e-883e-2d4d4763e34d}
        host: ${CLUSTER_PEER_3_HOST:localhost}
        port: ${CLUSTER_PEER_3_PORT:4002}
# Test Data
testdata:
  file: ${TEST_DATA_FILE:/Users/tienhungnguyen/private-repo/local-domain-manager/experiments/exp4/LDM1.json}
leader:
  election:
    mode: ${LEADER_ELECTION_MODE:DEFAULT}
    default-leader: ${DEFAULT_LEADER:66472086-5a7b-461e-883e-2d4d4763e34d}
