// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ping_pong.proto
// Protobuf Java Version: 4.28.3

package com.ldm.infrastructure.serialization.protobuf;

public final class PingPong {
  private PingPong() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      PingPong.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ldm.infrastructure.serialization.protobuf.Ping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ActorRef of the sender serialized as a string
     * </pre>
     *
     * <code>string replyTo = 1;</code>
     * @return The replyTo.
     */
    java.lang.String getReplyTo();
    /**
     * <pre>
     * ActorRef of the sender serialized as a string
     * </pre>
     *
     * <code>string replyTo = 1;</code>
     * @return The bytes for replyTo.
     */
    com.google.protobuf.ByteString
        getReplyToBytes();

    /**
     * <pre>
     * Start time in nanoseconds
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return The startTime.
     */
    long getStartTime();
  }
  /**
   * <pre>
   * Represents a Ping message
   * </pre>
   *
   * Protobuf type {@code com.ldm.infrastructure.serialization.protobuf.Ping}
   */
  public static final class Ping extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ldm.infrastructure.serialization.protobuf.Ping)
      PingOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Ping.class.getName());
    }
    // Use Ping.newBuilder() to construct.
    private Ping(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Ping() {
      replyTo_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ldm.infrastructure.serialization.protobuf.PingPong.Ping.class, com.ldm.infrastructure.serialization.protobuf.PingPong.Ping.Builder.class);
    }

    public static final int REPLYTO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object replyTo_ = "";
    /**
     * <pre>
     * ActorRef of the sender serialized as a string
     * </pre>
     *
     * <code>string replyTo = 1;</code>
     * @return The replyTo.
     */
    @java.lang.Override
    public java.lang.String getReplyTo() {
      java.lang.Object ref = replyTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replyTo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ActorRef of the sender serialized as a string
     * </pre>
     *
     * <code>string replyTo = 1;</code>
     * @return The bytes for replyTo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReplyToBytes() {
      java.lang.Object ref = replyTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private long startTime_ = 0L;
    /**
     * <pre>
     * Start time in nanoseconds
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(replyTo_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, replyTo_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(2, startTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(replyTo_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, replyTo_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ldm.infrastructure.serialization.protobuf.PingPong.Ping)) {
        return super.equals(obj);
      }
      com.ldm.infrastructure.serialization.protobuf.PingPong.Ping other = (com.ldm.infrastructure.serialization.protobuf.PingPong.Ping) obj;

      if (!getReplyTo()
          .equals(other.getReplyTo())) return false;
      if (getStartTime()
          != other.getStartTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REPLYTO_FIELD_NUMBER;
      hash = (53 * hash) + getReplyTo().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ldm.infrastructure.serialization.protobuf.PingPong.Ping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Represents a Ping message
     * </pre>
     *
     * Protobuf type {@code com.ldm.infrastructure.serialization.protobuf.Ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ldm.infrastructure.serialization.protobuf.Ping)
        com.ldm.infrastructure.serialization.protobuf.PingPong.PingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ldm.infrastructure.serialization.protobuf.PingPong.Ping.class, com.ldm.infrastructure.serialization.protobuf.PingPong.Ping.Builder.class);
      }

      // Construct using com.ldm.infrastructure.serialization.protobuf.PingPong.Ping.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        replyTo_ = "";
        startTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_descriptor;
      }

      @java.lang.Override
      public com.ldm.infrastructure.serialization.protobuf.PingPong.Ping getDefaultInstanceForType() {
        return com.ldm.infrastructure.serialization.protobuf.PingPong.Ping.getDefaultInstance();
      }

      @java.lang.Override
      public com.ldm.infrastructure.serialization.protobuf.PingPong.Ping build() {
        com.ldm.infrastructure.serialization.protobuf.PingPong.Ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ldm.infrastructure.serialization.protobuf.PingPong.Ping buildPartial() {
        com.ldm.infrastructure.serialization.protobuf.PingPong.Ping result = new com.ldm.infrastructure.serialization.protobuf.PingPong.Ping(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ldm.infrastructure.serialization.protobuf.PingPong.Ping result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.replyTo_ = replyTo_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.startTime_ = startTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ldm.infrastructure.serialization.protobuf.PingPong.Ping) {
          return mergeFrom((com.ldm.infrastructure.serialization.protobuf.PingPong.Ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ldm.infrastructure.serialization.protobuf.PingPong.Ping other) {
        if (other == com.ldm.infrastructure.serialization.protobuf.PingPong.Ping.getDefaultInstance()) return this;
        if (!other.getReplyTo().isEmpty()) {
          replyTo_ = other.replyTo_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                replyTo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                startTime_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object replyTo_ = "";
      /**
       * <pre>
       * ActorRef of the sender serialized as a string
       * </pre>
       *
       * <code>string replyTo = 1;</code>
       * @return The replyTo.
       */
      public java.lang.String getReplyTo() {
        java.lang.Object ref = replyTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          replyTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ActorRef of the sender serialized as a string
       * </pre>
       *
       * <code>string replyTo = 1;</code>
       * @return The bytes for replyTo.
       */
      public com.google.protobuf.ByteString
          getReplyToBytes() {
        java.lang.Object ref = replyTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          replyTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ActorRef of the sender serialized as a string
       * </pre>
       *
       * <code>string replyTo = 1;</code>
       * @param value The replyTo to set.
       * @return This builder for chaining.
       */
      public Builder setReplyTo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        replyTo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ActorRef of the sender serialized as a string
       * </pre>
       *
       * <code>string replyTo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReplyTo() {
        replyTo_ = getDefaultInstance().getReplyTo();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ActorRef of the sender serialized as a string
       * </pre>
       *
       * <code>string replyTo = 1;</code>
       * @param value The bytes for replyTo to set.
       * @return This builder for chaining.
       */
      public Builder setReplyToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        replyTo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <pre>
       * Start time in nanoseconds
       * </pre>
       *
       * <code>int64 startTime = 2;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <pre>
       * Start time in nanoseconds
       * </pre>
       *
       * <code>int64 startTime = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {

        startTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Start time in nanoseconds
       * </pre>
       *
       * <code>int64 startTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ldm.infrastructure.serialization.protobuf.Ping)
    }

    // @@protoc_insertion_point(class_scope:com.ldm.infrastructure.serialization.protobuf.Ping)
    private static final com.ldm.infrastructure.serialization.protobuf.PingPong.Ping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ldm.infrastructure.serialization.protobuf.PingPong.Ping();
    }

    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ping>
        PARSER = new com.google.protobuf.AbstractParser<Ping>() {
      @java.lang.Override
      public Ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Ping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ping> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ldm.infrastructure.serialization.protobuf.PingPong.Ping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PongOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ldm.infrastructure.serialization.protobuf.Pong)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Logical domain manager ID
     * </pre>
     *
     * <code>string ldmId = 1;</code>
     * @return The ldmId.
     */
    java.lang.String getLdmId();
    /**
     * <pre>
     * Logical domain manager ID
     * </pre>
     *
     * <code>string ldmId = 1;</code>
     * @return The bytes for ldmId.
     */
    com.google.protobuf.ByteString
        getLdmIdBytes();

    /**
     * <pre>
     * Start time in nanoseconds
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return The startTime.
     */
    long getStartTime();
  }
  /**
   * <pre>
   * Represents a Pong message
   * </pre>
   *
   * Protobuf type {@code com.ldm.infrastructure.serialization.protobuf.Pong}
   */
  public static final class Pong extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ldm.infrastructure.serialization.protobuf.Pong)
      PongOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Pong.class.getName());
    }
    // Use Pong.newBuilder() to construct.
    private Pong(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Pong() {
      ldmId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ldm.infrastructure.serialization.protobuf.PingPong.Pong.class, com.ldm.infrastructure.serialization.protobuf.PingPong.Pong.Builder.class);
    }

    public static final int LDMID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ldmId_ = "";
    /**
     * <pre>
     * Logical domain manager ID
     * </pre>
     *
     * <code>string ldmId = 1;</code>
     * @return The ldmId.
     */
    @java.lang.Override
    public java.lang.String getLdmId() {
      java.lang.Object ref = ldmId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ldmId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Logical domain manager ID
     * </pre>
     *
     * <code>string ldmId = 1;</code>
     * @return The bytes for ldmId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLdmIdBytes() {
      java.lang.Object ref = ldmId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ldmId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private long startTime_ = 0L;
    /**
     * <pre>
     * Start time in nanoseconds
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ldmId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, ldmId_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(2, startTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ldmId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, ldmId_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ldm.infrastructure.serialization.protobuf.PingPong.Pong)) {
        return super.equals(obj);
      }
      com.ldm.infrastructure.serialization.protobuf.PingPong.Pong other = (com.ldm.infrastructure.serialization.protobuf.PingPong.Pong) obj;

      if (!getLdmId()
          .equals(other.getLdmId())) return false;
      if (getStartTime()
          != other.getStartTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LDMID_FIELD_NUMBER;
      hash = (53 * hash) + getLdmId().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ldm.infrastructure.serialization.protobuf.PingPong.Pong prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Represents a Pong message
     * </pre>
     *
     * Protobuf type {@code com.ldm.infrastructure.serialization.protobuf.Pong}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ldm.infrastructure.serialization.protobuf.Pong)
        com.ldm.infrastructure.serialization.protobuf.PingPong.PongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ldm.infrastructure.serialization.protobuf.PingPong.Pong.class, com.ldm.infrastructure.serialization.protobuf.PingPong.Pong.Builder.class);
      }

      // Construct using com.ldm.infrastructure.serialization.protobuf.PingPong.Pong.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ldmId_ = "";
        startTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ldm.infrastructure.serialization.protobuf.PingPong.internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_descriptor;
      }

      @java.lang.Override
      public com.ldm.infrastructure.serialization.protobuf.PingPong.Pong getDefaultInstanceForType() {
        return com.ldm.infrastructure.serialization.protobuf.PingPong.Pong.getDefaultInstance();
      }

      @java.lang.Override
      public com.ldm.infrastructure.serialization.protobuf.PingPong.Pong build() {
        com.ldm.infrastructure.serialization.protobuf.PingPong.Pong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ldm.infrastructure.serialization.protobuf.PingPong.Pong buildPartial() {
        com.ldm.infrastructure.serialization.protobuf.PingPong.Pong result = new com.ldm.infrastructure.serialization.protobuf.PingPong.Pong(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ldm.infrastructure.serialization.protobuf.PingPong.Pong result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ldmId_ = ldmId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.startTime_ = startTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ldm.infrastructure.serialization.protobuf.PingPong.Pong) {
          return mergeFrom((com.ldm.infrastructure.serialization.protobuf.PingPong.Pong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ldm.infrastructure.serialization.protobuf.PingPong.Pong other) {
        if (other == com.ldm.infrastructure.serialization.protobuf.PingPong.Pong.getDefaultInstance()) return this;
        if (!other.getLdmId().isEmpty()) {
          ldmId_ = other.ldmId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                ldmId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                startTime_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object ldmId_ = "";
      /**
       * <pre>
       * Logical domain manager ID
       * </pre>
       *
       * <code>string ldmId = 1;</code>
       * @return The ldmId.
       */
      public java.lang.String getLdmId() {
        java.lang.Object ref = ldmId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ldmId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Logical domain manager ID
       * </pre>
       *
       * <code>string ldmId = 1;</code>
       * @return The bytes for ldmId.
       */
      public com.google.protobuf.ByteString
          getLdmIdBytes() {
        java.lang.Object ref = ldmId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ldmId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Logical domain manager ID
       * </pre>
       *
       * <code>string ldmId = 1;</code>
       * @param value The ldmId to set.
       * @return This builder for chaining.
       */
      public Builder setLdmId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ldmId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Logical domain manager ID
       * </pre>
       *
       * <code>string ldmId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLdmId() {
        ldmId_ = getDefaultInstance().getLdmId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Logical domain manager ID
       * </pre>
       *
       * <code>string ldmId = 1;</code>
       * @param value The bytes for ldmId to set.
       * @return This builder for chaining.
       */
      public Builder setLdmIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ldmId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <pre>
       * Start time in nanoseconds
       * </pre>
       *
       * <code>int64 startTime = 2;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <pre>
       * Start time in nanoseconds
       * </pre>
       *
       * <code>int64 startTime = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {

        startTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Start time in nanoseconds
       * </pre>
       *
       * <code>int64 startTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ldm.infrastructure.serialization.protobuf.Pong)
    }

    // @@protoc_insertion_point(class_scope:com.ldm.infrastructure.serialization.protobuf.Pong)
    private static final com.ldm.infrastructure.serialization.protobuf.PingPong.Pong DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ldm.infrastructure.serialization.protobuf.PingPong.Pong();
    }

    public static com.ldm.infrastructure.serialization.protobuf.PingPong.Pong getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pong>
        PARSER = new com.google.protobuf.AbstractParser<Pong>() {
      @java.lang.Override
      public Pong parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Pong> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pong> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ldm.infrastructure.serialization.protobuf.PingPong.Pong getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ping_pong.proto\022-com.ldm.infrastructur" +
      "e.serialization.protobuf\"*\n\004Ping\022\017\n\007repl" +
      "yTo\030\001 \001(\t\022\021\n\tstartTime\030\002 \001(\003\"(\n\004Pong\022\r\n\005" +
      "ldmId\030\001 \001(\t\022\021\n\tstartTime\030\002 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ldm_infrastructure_serialization_protobuf_Ping_descriptor,
        new java.lang.String[] { "ReplyTo", "StartTime", });
    internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ldm_infrastructure_serialization_protobuf_Pong_descriptor,
        new java.lang.String[] { "LdmId", "StartTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
